export const SET_PACK = 'SET_PACK';
export const GUIDE_LOADING = 'GUIDE_LOADING';
export const SET_GUIDE = 'SET_GUIDE';
export const FETCH_MY_PACKS = 'FETCH_MY_PACKS';
export const MY_PACKS_LOADING = 'MY_PACKS_LOADING';
export const CHEAT_SHEETS_LOADING = 'CHEAT_SHEETS_LOADING';
export const SET_CHEAT_SHEETS = 'SET_CHEAT_SHEETS';
export const REMOVE_PACK_LOADING = 'REMOVE_PACK_LOADING';
